# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintsns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('condition_type', models.PositiveSmallIntegerField(choices=[(0, '以上'), (1, '以下'), (2, '除外')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_home', models.BooleanField(default=False)),
                ('is_your_zone', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('use_home_post_scope', models.BooleanField(default=False)),
                ('is_included_post_scope', models.BooleanField(default=False)),
                ('post_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintsns.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='mintsns.StreamZone'),
        ),
        migrations.AddField(
            model_name='orcondition',
            name='stream_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_conditions', to='mintsns.StreamZone'),
        ),
        migrations.AddField(
            model_name='condition',
            name='or_condition_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='mintsns.OrCondition'),
        ),
    ]
