# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintsns', '0002_auto_20160515_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='mintsns.User'),
        ),
    ]
