# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintsns', '0003_stream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='mintsns.User'),
        ),
    ]
