# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintsns', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='GavePointUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('post', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='mintsns.Post')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='mintsns.User')),
            ],
        ),
    ]
