# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintsns', '0007_gavepointuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=62001)),
                ('image_thumbnail_url', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentGavePointUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='mintsns.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='PostGavePointUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gavepointuser',
            name='post',
        ),
        migrations.RemoveField(
            model_name='gavepointuser',
            name='user',
        ),
        migrations.AddField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 21, 34, 4, 504990)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 21, 34, 6, 896714)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 21, 34, 8, 648989)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 21, 34, 9, 920660)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 21, 34, 11, 191836)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 21, 34, 12, 279185)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 21, 34, 13, 488249)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 21, 34, 14, 704774)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 21, 34, 16, 8722)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 21, 34, 17, 134543)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 21, 34, 18, 240256)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 21, 34, 19, 960582)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GavePointUser',
        ),
        migrations.AddField(
            model_name='postgavepointuser',
            name='post',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='mintsns.Post'),
        ),
        migrations.AddField(
            model_name='postgavepointuser',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_gave_point_users', to='mintsns.User'),
        ),
        migrations.AddField(
            model_name='commentgavepointuser',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment_gave_point_users', to='mintsns.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='mintsns.User'),
        ),
    ]
